version: '3'

services:
  uber-api:
    env_file: ./.env
    command: "npm run dev"
    ports:
      - "8000:8000"
    volumes:
      - "./:/src"
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - mongodb:mongodb
  mongodb:
    image: mongo:3.4.6
    ports:
      - "27017:27017"
